spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    url: ${DATABASE_URL}
    password: ${DATABASE_PASS}
  h2:
    console:
      enabled: 'false # Disable if not using H2'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
sspring:
  application:
    name: chat-message
server:
  port: ${PORT:8081}
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: 'true'
